### ISSUE TITLE
Heating temperature read/set

### ISSUE THREAD

**Issue by mnaiman** [alexdelprete/HA-NeoPool-MQTT#16]
By the docs in Tasmota Neopool, it should be possible to read/write heating setpoint temperature.
Can this be done using MQTT?

https://tasmota.github.io/docs/NeoPool/#examples
Read Heating setpoint temperature

Here we read register MBF_PAR_HEATING_TEMP (0x0416):

Backlog NPResult 0;NPRead 0x416
RESULT = {"NPResult":0}
RESULT = {"NPRead":{"Address":1046,"Data":28}}

Thanks

**Comment by mnaiman** [comment]
Or it would be great to add that to main json of tasmota - neopool - @curzon01 What do you think?

**Comment by curzon01** [comment]
> Or it would be great to add that to main json of tasmota - neopool 

I don't want to have it within the module driver, otherwise the size of the ES8266 will grow out of control.

There would be solutions without adding it into the neopool module using Tasmota rules or Berry.

Do you use an ESP8266 or ESP32?

**Comment by mnaiman** [comment]
ESP32. This was my second thought to use Berry somehow and create new command.
I understand - limits, idea of json was that it would be most comfortable to use.

**Comment by mnaiman** [comment]
Perhaps general Berry command that read address and write address would be great.

Problem of current solution is, that I an issue command like that to read:
      service: mqtt.publish
      target: {}
      data:
        qos: 0
        retain: false
        topic: cmnd/SmartPool/Backlog
        payload: NPRead 0x416

But result is after some time in another topic(stat/SmartPool/RESULT) and when other backlog command is issued, it is non-deterministic which will be returned, so makes hard time to integrate to HA (or simply Im unaware how to do that :) )

**Comment by curzon01** [comment]
That's not the solution I have I have mind, pls be patient, will present the right way it but need some time...

**Comment by mnaiman** [comment]
Ok, no pressure, thanks for great solution as such!
Together with this repo, pool automation it waaaaay more professional than vendor provided app.

**Comment by curzon01** [comment]
The better solution would be

a) implement a new Tasmota command and 
b) append the new value to the Tasmota telemetry json topic `SENSOR` 

To implement the new Tasmota command 'NPHeatingTemp' and appended SENSOR value:

1. store the following Berry script as file `NPHeatingTemp.be` on your ESP32 (Tools -> Manage File system)
```berry
# Add command/data NPHeatingTemp to get/set Sugar Valley Heating Mode Temperature setpoint

MBF_PAR_HEATING_TEMP = 0x0416

import string
import json

# NeoPool command class
class NeoPool
  var heating_temperature

  def read_register(cmd, read_cmnd, addr, cnt)
    var res = tasmota.cmd(string.format("%s 0x%04X,%d", read_cmnd, addr, cnt), true).find(read_cmnd, "Unknown")
    # result must be a json
    if "Unknown" == res
      tasmota.resp_cmnd(string.format('{"%s":"NeoPool module not available or not activated"}', cmd))
      return nil
    end
    var _json = json.load(json.dump(res))
    if nil == _json || "Error" == res
      tasmota.resp_cmnd(string.format('{"%s":"NeoPool device does not respond"}', cmd))
      return nil
    end
    return compile("return ".._json.find('Data'))()
  end

  def get_heating_temperature(cmd)
    self.heating_temperature = self.read_register(cmd, "NPRead", MBF_PAR_HEATING_TEMP) & 0xff
  end

  def json_append()
    tasmota.response_append(',"HeatingTemp":'+str(self.heating_temperature))
    tasmota.set_timer(5000, / -> self.get_heating_temperature('json_append()'))
  end

  # NPHeatingTemp <temperature>
  def NPHeatingTemp(cmd, idx, payload)
    if nil != payload && "" != payload
      if int(payload) <= 50 && int(payload) >= 1
        var temp_reg = self.read_register(cmd, "NPRead", MBF_PAR_HEATING_TEMP) & 0xff00 | int(payload)
        tasmota.cmd(string.format("NPWrite 0x%04X,%d", MBF_PAR_HEATING_TEMP, temp_reg), true)
        tasmota.cmd("NPExec", true)
      else
        tasmota.resp_cmnd_error()
        return
      end
    end
    self.get_heating_temperature(cmd)
    tasmota.resp_cmnd(string.format('{"%s":%d}', cmd, self.heating_temperature))
  end

  def init()
    tasmota.add_cmd('NPHeatingTemp', / cmd, idx, payload -> self.NPHeatingTemp(cmd, idx, payload))
    self.get_heating_temperature('init()')
  end

  def deinit()
    tasmota.remove_cmd('NPHeatingTemp')
  end
end

# register driver
np = NeoPool()
tasmota.add_driver(np)

# for Berry console debugging only
# self = np
```
2. make it automatically available when your ESP32 starts by creating an additonal file `autoexec.be` with the content
```berry
load("NPHeatingTemp.be")
```
3. load the `NPHeatingTemp.be` by exec `load("NPHeatingTemp.be")` within Tasmota Berry Scripting console or restart your ESP32

4. now new Tasmota command `NPHeatingTemp` should be available, also the TelePeriod topic contains now a `NPHeatingTemp` value

5. Add new command and SENSOR value to HA as a number entity using MQTT integration:
```yaml
mqtt:
  number:
    - unique_id: "mqtt_oxilfe_heating_temperature"
      name: "MQTT Oxilife Heating Temperature"
      device_class: temperature
      unit_of_measurement: "°C"
      min: 1
      max: 50
      step: 1
      mode: slider
      state_topic: "tele/SmartPool/SENSOR"
      value_template: >-
        {{ value_json.HeatingTemp|int if value_json.HeatingTemp is defined else this.state }}
      command_topic: "cmnd/SmartPool/NPHeatingTemp"
      availability_topic: "tele/SmartPool/LWT"
      payload_available: "Online"
      payload_not_available: "Offline"
```

One note:
Since we can't query the current HeatingTemp value (read out register 0x416)  within the json_append() class method before Tasmota sends the SENSOR topic - this is not possible with the current berry implementation on Tasmota, we would just get garbage for the SENSOR topic if we do that - the current HeatingTemp value is periodically read every TelePeriod time, 5 seconds after Tasmota sends the TelePeriod SENSOR topic. 

This will cause a delay between the actual value and the displayed value within HA of max. "TelePeriod" seconds, if you change the value on your system.
So for example if you use `TelePeriod 60` and manually change the value on your sytem using the build-in display, it could be wrong displayed in HA with the older value for max 60 seconds - but I think we can live with that.
